//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.12
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// Alex Lotz (lotz@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef _COMMPARAMETER_IDL_ENUM_PARAMRESPONSETYPE
#define _COMMPARAMETER_IDL_ENUM_PARAMRESPONSETYPE

#include <ace/CDR_Stream.h>

namespace CommParameterIDL
{
enum ENUM_INTERNAL_ParamResponseType
{
	LITERAL_BUSY, LITERAL_INVALID, LITERAL_OK
};

typedef ACE_CDR::Long ENUM_ParamResponseType;
}
;
#endif
