//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.12
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// Alex Lotz (lotz@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef _COMMPARAMETER_IDL_COMMPARAMETERRESPONSE
#define _COMMPARAMETER_IDL_COMMPARAMETERRESPONSE

// include IDL's
#include "smartEnumParamResponseTypeBase.hh"
#include <vector>

#include <ace/CDR_Stream.h>
#include <ace/SString.h>

namespace CommParameterIDL
{
struct CommParameterResponse
{
	ENUM_ParamResponseType response;
};
}
;
#endif
