#!/bin/bash

  if test -e $SMART_ROOT_ACE/bin/NamingService/AceSmartSoftNamingServiceList
  then
    $SMART_ROOT_ACE/bin/NamingService/AceSmartSoftNamingServiceList
  else
    if test -e /usr/bin/AceSmartSoftNamingServiceList
    then
      /usr/bin/AceSmartSoftNamingServiceList
    else
      echo "ERROR: could not find /usr/bin/AceSmartSoftNamingServiceList!"
    fi
  fi  
