#!/bin/bash

  if test -e $SMART_ROOT_ACE/bin/NamingService/AceSmartSoftNamingService
  then
    $SMART_ROOT_ACE/bin/NamingService/AceSmartSoftNamingService
  else
    if test -e /usr/bin/AceSmartSoftNamingService
    then
      /usr/bin/AceSmartSoftNamingService
    else
      echo "ERROR: could not find /usr/bin/AceSmartSoftNamingService!"
    fi
  fi  
