#!/bin/bash

# compare to 3 because 1st is the script name itself, 2nd is the grep call and 3rd is the actual binary SmartSoftNamingService
if [ `ps -Al | grep -c SmartSoftNaming` -eq 1 ]
then 
  echo "shuttting down SmartSoft Naming Service ..."
  killall SmartSoftNamingService
  if test -e /tmp/SMART_NAMES
  then 
    rm /tmp/SMART_NAMES
  fi
  echo "SmartSoft Naming Service is down!"
else 
  echo "SmartSoft Naming Service is not running!"
fi
